### ISSUE TITLE
VerifyAuthNode-1.3.8 not working with AM 7.5.0

### ISSUE THREAD

**Issue by Biswajit0180** [ForgeRock/Twilio-Verify-Auth-Tree-Nodes#17]
VerifyAuthNode-1.3.8 not working with AM 7.5.0, its giving below error, could it possible to get compatible jar for AM 7.5.0 @BrunoLavitForgerock @TylerGelinas  

 java.lang.NoSuchMethodError: 'com.sun.identity.idm.AMIdentity org.forgerock.openam.core.CoreWrapper.getIdentity(java.lang.String, java.lang.String)'

**Comment by ghyslaindetry** [comment]
I confirm this statement.

In fact, this doesn't exist in org.forgerock.openam.core.CoreWrapper : convertRealmPathToRealmDn

**Comment by jheiselman** [comment]
I contacted support about this issue and they said that you have to use 1.4.25, however, they have not published any compiled artifacts for that version, which leaves it up to the end user to do.
